### ISSUE TITLE
Cart View

### ISSUE THREAD

**Issue by daniellearquisola** [Bubble-sort-Tape/GraceShopper#1]
As a user, I should be able to see items in my cart and the total price before I checkout. 

Sub-tasks: 
- [x] Create Cart React Component #2 
- [x] Create Cart Redux Sub-reducer #17 
- [x] Create Cart Express Route #18
