### ISSUE TITLE
Checkout Items in Cart

### ISSUE THREAD

**Issue by moondrek** [Bubble-sort-Tape/GraceShopper#10]
As a customer/visitor, I want to be able to "checkout" the items in my cart so I can purchase my desired goods.
* Think of a typical user experience on popular websites from a guest user and logged-in user perspective.
* You can just start with by simulating the experience of checking out with a simple confirmation page.

- [x] Checkout React Component #48
- [ ] Checkout Redux Thunk #49
- [ ] Checkout Express Route #50
- [ ] Checkout Redux Action and Sub-Reducer #51
- [ ] Confirm Checkout React Component #52
- [x] Order Database Model #27
