### ISSUE TITLE
Create an Account

### ISSUE THREAD

**Issue by moondrek** [Bubble-sort-Tape/GraceShopper#11]
As a customer/visitor, I want to be able to create an account so I can have a logged-in experience.

- [ ] Create Account React Component #53
- [ ] Log-In React Component #54
- [ ] Create Account Express Route #55
- [ ] Log-In Express Route #56
- [x] User Model #22
