### ISSUE TITLE
Admin Backend Product Routes

### ISSUE THREAD

**Issue by moondrek** [Bubble-sort-Tape/GraceShopper#13]
As an administrator, I want to be able to have full rights to make backend requests to add, edit, and remove products.

No one else should have access.

- [ ] Add Product API Route #59

- [ ] Edit Product API Route #60

- [ ] Delete Product API Route #61
