### ISSUE TITLE
All Products View

### ISSUE THREAD

**Issue by moondrek** [Bubble-sort-Tape/GraceShopper#6]
As a customer/visitor I want to be able to view all available products so I can pick from a variety.

- [x] All Products React Component #21 
- [x] All Products Redux Store #23
- [x] All Products Express Route #26
- [x] Products Database Model #24
