### ISSUE TITLE
Single Product View

### ISSUE THREAD

**Issue by moondrek** [Bubble-sort-Tape/GraceShopper#7]
As a customer/visitor I want to be able to view a single product so I can see more details.

- [x] Single Product React Component #20 
- [x] Single Product Redux Store: #32 
- [x] Single Product Express Route #33
- [x] Products Database Model #24
