### ISSUE TITLE
Add Product to Cart

### ISSUE THREAD

**Issue by moondrek** [Bubble-sort-Tape/GraceShopper#8]
As a customer/visitor, I want to be able to add a product to my cart so I can collect my desired products in one place.

- [ ] Add Product Component #38
- [ ] Add Product Redux Thunk #39
- [ ] Add Product Express Route #40
