### ISSUE TITLE
Edit Cart

### ISSUE THREAD

**Issue by moondrek** [Bubble-sort-Tape/GraceShopper#9]
As a customer/visitor, I want to be able to edit my cart if I change my mind:

* change the quantity of a product in my cart.
* remove a product in my cart.
* No one else should be able to edit my cart except me.

- [x] Edit Cart Component #41
- [ ] Edit Product-in-Cart Redux Thunk #42
- [ ] Edit Product-in-Cart Express Route #43
- [ ] Edit Product-in-Cart Redux Action & Sub-Reducer

- [ ] Remove Product-in-Cart Redux Thunk #45
- [ ] Remove Product-in-Cart Express Route #46
- [ ] Remove Product-in-Cart Redux Action & Sub-Reducer #47
